version: 0.0
os: windows

files:
  - source: build
    destination: C:\inetpub\wwwroot

hooks:
  BeforeInstall:
    - location: .\scripts\StopIIS.ps1
  AfterInstall:
    - location: .\scripts\StartIIS.ps1
