version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22.9.0
    commands:
      - echo Installing Node.js and dependencies...
      - aws codeartifact login --tool npm --repository pipe-packages --domain pipe-domain --domain-owner 266735819128 --region eu-west-1
      - npm install

  build:
    commands:
      - echo Building the React app...
      - npm run build # Build the app

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - build/** # Include all files in the build directory
  discard-paths: yes # This is typically set to yes to avoid directory structure
