version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22.9.0
    commands:
      - echo Installing Node.js and dependencies...
      - npm login
      - npm install # Install dependencies

  build:
    commands:
      - echo Building the React app...
      - npm run build # Build the app

artifacts:
  files:
    - build/** # Include all files in the build directory
  discard-paths: yes # This is typically set to yes to avoid directory structure
